/*
 Navicat MySQL Data Transfer

 Source Server         : 10.175.5.59_0
 Source Server Type    : MySQL
 Source Server Version : 80030
 Source Host           : 10.175.5.59:0
 Source Schema         : zxltest

 Target Server Type    : MySQL
 Target Server Version : 80030
 File Encoding         : 65001

 Date: 05/01/2024 08:16:18
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for model
-- ----------------------------
DROP TABLE IF EXISTS `model`;
CREATE TABLE `model`  (
  `model` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_vietnamese_ci NULL DEFAULT NULL,
  `connect` int(0) NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8mb3 COLLATE = utf8mb3_vietnamese_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of model
-- ----------------------------
INSERT INTO `model` VALUES ('1', 1);
INSERT INTO `model` VALUES ('HDT628', NULL);
INSERT INTO `model` VALUES ('HDT647', NULL);
INSERT INTO `model` VALUES ('HDT655', NULL);
INSERT INTO `model` VALUES ('IHT911', NULL);
INSERT INTO `model` VALUES ('Default', NULL);
INSERT INTO `model` VALUES ('Holtek', NULL);
INSERT INTO `model` VALUES ('HDT646', NULL);
INSERT INTO `model` VALUES ('HDT766', NULL);
INSERT INTO `model` VALUES ('HDT789', NULL);
INSERT INTO `model` VALUES ('HDT001', NULL);
INSERT INTO `model` VALUES ('HDT660', NULL);
INSERT INTO `model` VALUES ('HDT725', NULL);
INSERT INTO `model` VALUES ('HDT880', NULL);
INSERT INTO `model` VALUES ('ISB901', NULL);
INSERT INTO `model` VALUES ('HDT858', NULL);
INSERT INTO `model` VALUES ('HDT828', NULL);
INSERT INTO `model` VALUES ('ISB900', NULL);
INSERT INTO `model` VALUES ('HDT655-SMT', NULL);
INSERT INTO `model` VALUES ('HDT646', NULL);
INSERT INTO `model` VALUES ('IHT911-SMT', NULL);
INSERT INTO `model` VALUES ('', NULL);
INSERT INTO `model` VALUES ('HDT646-SMT', NULL);
INSERT INTO `model` VALUES ('Holtek-SMT', NULL);
INSERT INTO `model` VALUES ('HDT858SMT', NULL);
INSERT INTO `model` VALUES ('HDT858-SMT', NULL);
INSERT INTO `model` VALUES ('HDT647-SMT', NULL);
INSERT INTO `model` VALUES ('IBC919', NULL);
INSERT INTO `model` VALUES ('HDT660-SMT', NULL);
INSERT INTO `model` VALUES ('HDT766-SMT', NULL);
INSERT INTO `model` VALUES ('HDT789-SMT', NULL);
INSERT INTO `model` VALUES ('ISB901-SMT', NULL);
INSERT INTO `model` VALUES ('ISB900-SMT', NULL);
INSERT INTO `model` VALUES ('HDT628-SMT', NULL);
INSERT INTO `model` VALUES ('WCP052', NULL);
INSERT INTO `model` VALUES ('DyTest', NULL);
INSERT INTO `model` VALUES ('DT789', NULL);
INSERT INTO `model` VALUES ('HDT647', NULL);
INSERT INTO `model` VALUES ('HDT608-SMT', NULL);
INSERT INTO `model` VALUES ('HDT647', NULL);
INSERT INTO `model` VALUES ('HDT647', NULL);
INSERT INTO `model` VALUES ('ICP002-SMT', NULL);
INSERT INTO `model` VALUES ('HDT628', NULL);
INSERT INTO `model` VALUES ('HDT900-SMT', NULL);
INSERT INTO `model` VALUES ('HDT606', NULL);
INSERT INTO `model` VALUES ('ICP002', NULL);
INSERT INTO `model` VALUES ('HDT627-SMT', NULL);
INSERT INTO `model` VALUES ('HDT002', NULL);
INSERT INTO `model` VALUES ('HDT655', NULL);
INSERT INTO `model` VALUES ('HDT627TICO', NULL);
INSERT INTO `model` VALUES ('HDT627', NULL);
INSERT INTO `model` VALUES ('HDT627', NULL);
INSERT INTO `model` VALUES ('STM32', NULL);
INSERT INTO `model` VALUES ('HDT527', NULL);
INSERT INTO `model` VALUES ('HDT668', NULL);
INSERT INTO `model` VALUES ('HDT660', NULL);
INSERT INTO `model` VALUES ('HDT660', NULL);
INSERT INTO `model` VALUES ('HDT660', NULL);
INSERT INTO `model` VALUES ('VCS001', NULL);
INSERT INTO `model` VALUES ('IHT911', NULL);
INSERT INTO `model` VALUES ('HDT608', NULL);
INSERT INTO `model` VALUES ('VCS001-SMT', NULL);
INSERT INTO `model` VALUES ('HDT725', NULL);
INSERT INTO `model` VALUES ('HDT565-SMT', NULL);
INSERT INTO `model` VALUES ('HDT660', NULL);
INSERT INTO `model` VALUES ('HDT565', NULL);
INSERT INTO `model` VALUES ('HDT655', NULL);

SET FOREIGN_KEY_CHECKS = 1;
